#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranPhoto
@end

@interface SystranPhoto : SystranObject

/* Label [optional]
 */
@property(nonatomic) NSString* title;
/* Height [optional]
 */
@property(nonatomic) NSNumber* height;
/* Width [optional]
 */
@property(nonatomic) NSNumber* width;
/* URL 
 */
@property(nonatomic) NSString* url;

@end
