#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranDescription
@end

@interface SystranDescription : SystranObject

/* Description part content 
 */
@property(nonatomic) NSString* content;
/* Description part category 
 */
@property(nonatomic) NSString* type;

@end
