#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranBooking
@end

@interface SystranBooking : SystranObject

/* Booking service url 
 */
@property(nonatomic) NSString* url;

@end
