#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranReview
@end

@interface SystranReview : SystranObject

/* Text [optional]
 */
@property(nonatomic) NSString* text;
/* Language [optional]
 */
@property(nonatomic) NSString* language;
/* Author [optional]
 */
@property(nonatomic) NSString* author;
/* Rating [optional]
 */
@property(nonatomic) NSNumber* rating;

@end
