#import <Foundation/Foundation.h>
#import "SystranInspirationResponse.h"
#import "SystranInspirationDetailsResponse.h"
#import "SystranObject.h"
#import "SystranApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SystranInspirationsApi: NSObject

@property(nonatomic, assign)SystranApiClient *apiClient;

-(instancetype) initWithApiClient:(SystranApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SystranInspirationsApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SystranInspirationsApi*) sharedAPI;
///
///
/// List dossiers
/// Get a list of `Inspirations` of type `dossier`.\n\nThe main criteria can be:\n* a position and a radius\n* a textual search\n\nAdditional critera can be added.
///
/// @param latitude Latitude location
/// @param longitude Longitude location
/// @param radius Radius in meters
/// @param address Address
/// @param country Country
/// @param state State
/// @param county County
/// @param city City
/// @param district District
/// @param postalCode Postal Code
/// @param limit Pagination limit
/// @param offset Pagination offset
/// @param acceptLanguage Preferred languages for response localization.\n\nSee [Accept-Language header specification for HTTP\n1.1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4)
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranInspirationResponse*
-(NSNumber*) geographicInspirationsDossiersListGetWithCompletionBlock :(NSNumber*) latitude 
     longitude:(NSNumber*) longitude 
     radius:(NSNumber*) radius 
     address:(NSString*) address 
     country:(NSString*) country 
     state:(NSString*) state 
     county:(NSString*) county 
     city:(NSString*) city 
     district:(NSString*) district 
     postalCode:(NSString*) postalCode 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     acceptLanguage:(NSString*) acceptLanguage 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranInspirationResponse* output, NSError* error))completionBlock;
    


///
///
/// List events
/// Get a list of `Inspirations` of type `event`.\n\nThe main criteria can be:\n* a position and a radius\n* a textual search\n\nAdditional critera can be added.
///
/// @param latitude Latitude location
/// @param longitude Longitude location
/// @param radius Radius in meters
/// @param address Address
/// @param country Country
/// @param state State
/// @param county County
/// @param city City
/// @param district District
/// @param postalCode Postal Code
/// @param limit Pagination limit
/// @param offset Pagination offset
/// @param acceptLanguage Preferred languages for response localization.\n\nSee [Accept-Language header specification for HTTP\n1.1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4)
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranInspirationResponse*
-(NSNumber*) geographicInspirationsEventsListGetWithCompletionBlock :(NSNumber*) latitude 
     longitude:(NSNumber*) longitude 
     radius:(NSNumber*) radius 
     address:(NSString*) address 
     country:(NSString*) country 
     state:(NSString*) state 
     county:(NSString*) county 
     city:(NSString*) city 
     district:(NSString*) district 
     postalCode:(NSString*) postalCode 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     acceptLanguage:(NSString*) acceptLanguage 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranInspirationResponse* output, NSError* error))completionBlock;
    


///
///
/// Get a specific Inspiration
/// Get a specific `Inspiration`.
///
/// @param _id Inspiration identifier
/// @param acceptLanguage Preferred languages for response localization.\n\nSee [Accept-Language header specification for HTTP\n1.1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4)
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranInspirationDetailsResponse*
-(NSNumber*) geographicInspirationsGetGetWithCompletionBlock :(NSString*) _id 
     acceptLanguage:(NSString*) acceptLanguage 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranInspirationDetailsResponse* output, NSError* error))completionBlock;
    


///
///
/// List Inspirations
/// Get a list of `Inspirations`.\n\nThe main criteria can be:\n* a position and a radius\n* a textual search\n\nAdditional critera can be added.
///
/// @param latitude Latitude location
/// @param longitude Longitude location
/// @param radius Radius in meters
/// @param address Address
/// @param country Country
/// @param state State
/// @param county County
/// @param city City
/// @param district District
/// @param postalCode Postal Code
/// @param limit Pagination limit
/// @param offset Pagination offset
/// @param acceptLanguage Preferred languages for response localization.\n\nSee [Accept-Language header specification for HTTP\n1.1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4)
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranInspirationResponse*
-(NSNumber*) geographicInspirationsListGetWithCompletionBlock :(NSNumber*) latitude 
     longitude:(NSNumber*) longitude 
     radius:(NSNumber*) radius 
     address:(NSString*) address 
     country:(NSString*) country 
     state:(NSString*) state 
     county:(NSString*) county 
     city:(NSString*) city 
     district:(NSString*) district 
     postalCode:(NSString*) postalCode 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     acceptLanguage:(NSString*) acceptLanguage 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranInspirationResponse* output, NSError* error))completionBlock;
    


///
///
/// List news in brief
/// Get a list of `Inspirations` of type `news in brief`.\n\nThe main criteria can be:\n* a position and a radius\n* a textual search\n\nAdditional critera can be added.
///
/// @param latitude Latitude location
/// @param longitude Longitude location
/// @param radius Radius in meters
/// @param address Address
/// @param country Country
/// @param state State
/// @param county County
/// @param city City
/// @param district District
/// @param postalCode Postal Code
/// @param limit Pagination limit
/// @param offset Pagination offset
/// @param acceptLanguage Preferred languages for response localization.\n\nSee [Accept-Language header specification for HTTP\n1.1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4)
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranInspirationResponse*
-(NSNumber*) geographicInspirationsNewsInBriefListGetWithCompletionBlock :(NSNumber*) latitude 
     longitude:(NSNumber*) longitude 
     radius:(NSNumber*) radius 
     address:(NSString*) address 
     country:(NSString*) country 
     state:(NSString*) state 
     county:(NSString*) county 
     city:(NSString*) city 
     district:(NSString*) district 
     postalCode:(NSString*) postalCode 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     acceptLanguage:(NSString*) acceptLanguage 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranInspirationResponse* output, NSError* error))completionBlock;
    


///
///
/// List slide shows
/// Get a list of `Inspirations` of type `slide show`.\n\nThe main criteria can be:\n* a position and a radius\n* a textual search\n\nAdditional critera can be added.
///
/// @param latitude Latitude location
/// @param longitude Longitude location
/// @param radius Radius in meters
/// @param address Address
/// @param country Country
/// @param state State
/// @param county County
/// @param city City
/// @param district District
/// @param postalCode Postal Code
/// @param limit Pagination limit
/// @param offset Pagination offset
/// @param acceptLanguage Preferred languages for response localization.\n\nSee [Accept-Language header specification for HTTP\n1.1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4)
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranInspirationResponse*
-(NSNumber*) geographicInspirationsSlideShowsListGetWithCompletionBlock :(NSNumber*) latitude 
     longitude:(NSNumber*) longitude 
     radius:(NSNumber*) radius 
     address:(NSString*) address 
     country:(NSString*) country 
     state:(NSString*) state 
     county:(NSString*) county 
     city:(NSString*) city 
     district:(NSString*) district 
     postalCode:(NSString*) postalCode 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     acceptLanguage:(NSString*) acceptLanguage 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranInspirationResponse* output, NSError* error))completionBlock;
    


///
///
/// List tests
/// Get a list of `Inspirations` of type `test`.\n\nThe main criteria can be:\n* a position and a radius\n* a textual search\n\nAdditional critera can be added.
///
/// @param latitude Latitude location
/// @param longitude Longitude location
/// @param radius Radius in meters
/// @param address Address
/// @param country Country
/// @param state State
/// @param county County
/// @param city City
/// @param district District
/// @param postalCode Postal Code
/// @param limit Pagination limit
/// @param offset Pagination offset
/// @param acceptLanguage Preferred languages for response localization.\n\nSee [Accept-Language header specification for HTTP\n1.1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4)
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranInspirationResponse*
-(NSNumber*) geographicInspirationsTestsListGetWithCompletionBlock :(NSNumber*) latitude 
     longitude:(NSNumber*) longitude 
     radius:(NSNumber*) radius 
     address:(NSString*) address 
     country:(NSString*) country 
     state:(NSString*) state 
     county:(NSString*) county 
     city:(NSString*) city 
     district:(NSString*) district 
     postalCode:(NSString*) postalCode 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     acceptLanguage:(NSString*) acceptLanguage 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranInspirationResponse* output, NSError* error))completionBlock;
    



@end
