#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranLiteLocation.h"


@protocol SystranLitePOI
@end

@interface SystranLitePOI : SystranObject

/* POI Identifier 
 */
@property(nonatomic) NSString* _id;
/* Location 
 */
@property(nonatomic) SystranLiteLocation* location;
/* Name [optional]
 */
@property(nonatomic) NSString* name;
/* Main type 
 */
@property(nonatomic) NSString* mainType;
/* Types, ordered from general to specific 
 */
@property(nonatomic) NSArray* /* NSString */ types;
/* Rating [optional]
 */
@property(nonatomic) NSNumber* rating;
/* Price Level [optional]
 */
@property(nonatomic) NSNumber* priceLevel;

@end
