#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranPOIAddressComponents
@end

@interface SystranPOIAddressComponents : SystranObject

/* Country [optional]
 */
@property(nonatomic) NSString* country;
/* State [optional]
 */
@property(nonatomic) NSString* state;
/* County [optional]
 */
@property(nonatomic) NSString* county;
/* City [optional]
 */
@property(nonatomic) NSString* city;
/* District [optional]
 */
@property(nonatomic) NSString* district;
/* Postal code [optional]
 */
@property(nonatomic) NSString* postalCode;
/* Street [optional]
 */
@property(nonatomic) NSString* street;
/* House [optional]
 */
@property(nonatomic) NSString* house;

@end
