#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranMail
@end

@interface SystranMail : SystranObject

/* Mail address 
 */
@property(nonatomic) NSString* value;
/* Professional, ... [optional]
 */
@property(nonatomic) NSString* type;

@end
