#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranAddressComponents.h"


@protocol SystranAddress
@end

@interface SystranAddress : SystranObject

/* Address components [optional]
 */
@property(nonatomic) SystranAddressComponents* components;
/* Formatted Address (Postal Address) [optional]
 */
@property(nonatomic) NSString* formatted;

@end
