#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranMail.h"
#import "SystranPhoneNumber.h"


@protocol SystranContact
@end

@interface SystranContact : SystranObject

/* Array of phone numbers [optional]
 */
@property(nonatomic) NSArray<SystranPhoneNumber>* phoneNumbers;
/* Array of mails [optional]
 */
@property(nonatomic) NSArray<SystranMail>* mails;

@end
