#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranFullPOI.h"
#import "SystranErrorResponse.h"


@protocol SystranPoiDetailsResponse
@end

@interface SystranPoiDetailsResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Full POI data 
 */
@property(nonatomic) SystranFullPOI* result;

@end
