#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranPosition.h"


@protocol SystranLiteLocation
@end

@interface SystranLiteLocation : SystranObject

/* Position defined by latitude and longitude 
 */
@property(nonatomic) SystranPosition* position;
/* Vicinity description [optional]
 */
@property(nonatomic) NSString* vicinity;

@end
