#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranVideo
@end

@interface SystranVideo : SystranObject

/* Label [optional]
 */
@property(nonatomic) NSString* title;
/* URL 
 */
@property(nonatomic) NSString* url;

@end
