#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranPhoneNumber
@end

@interface SystranPhoneNumber : SystranObject

/* Raw phone number 
 */
@property(nonatomic) NSString* value;
/* Formatted phone number [optional]
 */
@property(nonatomic) NSString* formatted;
/* International phone number [optional]
 */
@property(nonatomic) NSString* international;
/* Professional, Fax, Mobile, ... [optional]
 */
@property(nonatomic) NSString* type;

@end
