#import <Foundation/Foundation.h>
#import "SystranDestinationDetailsResponse.h"
#import "SystranDestinationResponse.h"
#import "SystranObject.h"
#import "SystranApiClient.h"


/**
 * NOTE: This class is auto generated by the swagger code generator program. 
 * https://github.com/swagger-api/swagger-codegen 
 * Do not edit the class manually.
 */

@interface SystranDestinationsApi: NSObject

@property(nonatomic, assign)SystranApiClient *apiClient;

-(instancetype) initWithApiClient:(SystranApiClient *)apiClient;
-(void) addHeader:(NSString*)value forKey:(NSString*)key;
-(unsigned long) requestQueueSize;
+(SystranDestinationsApi*) apiWithHeader:(NSString*)headerValue key:(NSString*)key;
+(SystranDestinationsApi*) sharedAPI;
///
///
/// Get a specific Destination
/// Get a specific `Destination`.
///
/// @param _id Destination identifier
/// @param acceptLanguage Preferred languages for response localization.\n\nSee [Accept-Language header specification for HTTP\n1.1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4)
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranDestinationDetailsResponse*
-(NSNumber*) geographicDestinationsGetGetWithCompletionBlock :(NSString*) _id 
     acceptLanguage:(NSString*) acceptLanguage 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranDestinationDetailsResponse* output, NSError* error))completionBlock;
    


///
///
/// List Destinations
/// Get a list of `Destinations`.\n\nThe main criteria can be:\n* a position and a radius\n* a textual search\n\nAdditional critera can be added.
///
/// @param latitude Latitude location
/// @param longitude Longitude location
/// @param radius Radius in meters
/// @param address Address
/// @param country Country
/// @param state State
/// @param county County
/// @param city City
/// @param district District
/// @param postalCode Postal Code
/// @param limit Pagination limit
/// @param offset Pagination offset
/// @param acceptLanguage Preferred languages for response localization.\n\nSee [Accept-Language header specification for HTTP\n1.1](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4)
/// @param callback Javascript callback function name for JSONP Support
/// 
///
/// @return SystranDestinationResponse*
-(NSNumber*) geographicDestinationsListGetWithCompletionBlock :(NSNumber*) latitude 
     longitude:(NSNumber*) longitude 
     radius:(NSNumber*) radius 
     address:(NSString*) address 
     country:(NSString*) country 
     state:(NSString*) state 
     county:(NSString*) county 
     city:(NSString*) city 
     district:(NSString*) district 
     postalCode:(NSString*) postalCode 
     limit:(NSNumber*) limit 
     offset:(NSNumber*) offset 
     acceptLanguage:(NSString*) acceptLanguage 
     callback:(NSString*) callback 
    
    completionHandler: (void (^)(SystranDestinationResponse* output, NSError* error))completionBlock;
    



@end
