#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranPOIAddressComponents.h"


@protocol SystranPOIAddress
@end

@interface SystranPOIAddress : SystranObject

/* Address components [optional]
 */
@property(nonatomic) SystranPOIAddressComponents* components;
/* Formatted Address (Postal Address) [optional]
 */
@property(nonatomic) NSString* formatted;
/* Vicinity [optional]
 */
@property(nonatomic) NSString* vicinity;

@end
