#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranFullDestination.h"
#import "SystranErrorResponse.h"


@protocol SystranDestinationDetailsResponse
@end

@interface SystranDestinationDetailsResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Full Destination data 
 */
@property(nonatomic) SystranFullDestination* result;

@end
