#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranFullLocation.h"
#import "SystranPhoto.h"
#import "SystranVideo.h"


@protocol SystranFullInspiration
@end

@interface SystranFullInspiration : SystranObject

/* Inspiration Identifier 
 */
@property(nonatomic) NSString* _id;
/* Location 
 */
@property(nonatomic) SystranFullLocation* location;
/* Inspiration type 
 */
@property(nonatomic) NSString* type;
/* Title 
 */
@property(nonatomic) NSString* title;
/* Introduction 
 */
@property(nonatomic) NSString* introduction;
/* Content 
 */
@property(nonatomic) NSString* content;
/* Array of Photos [optional]
 */
@property(nonatomic) NSArray<SystranPhoto>* photos;
/* Array of Videos [optional]
 */
@property(nonatomic) NSArray<SystranVideo>* videos;

@end
