#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranFullInspiration.h"
#import "SystranErrorResponse.h"


@protocol SystranInspirationDetailsResponse
@end

@interface SystranInspirationDetailsResponse : SystranObject

/* Error at request level [optional]
 */
@property(nonatomic) SystranErrorResponse* error;
/* Full Inspiration data 
 */
@property(nonatomic) SystranFullInspiration* result;

@end
