#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol SystranOpeningDates
@end

@interface SystranOpeningDates : SystranObject

/* Begin date 
 */
@property(nonatomic) NSString* begin;
/* End date 
 */
@property(nonatomic) NSString* end;

@end
