#import <Foundation/Foundation.h>
#import "SystranObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "SystranAddress.h"
#import "SystranFullPosition.h"
#import "SystranBoundaries.h"


@protocol SystranFullLocation
@end

@interface SystranFullLocation : SystranObject

/* Boundaries defined by a polygon composed of a list of coordinates [optional]
 */
@property(nonatomic) SystranBoundaries* boundaries;
/* Position defined by coordinates and type 
 */
@property(nonatomic) SystranFullPosition* position;
/* Address [optional]
 */
@property(nonatomic) SystranAddress* address;

@end
